### ISSUE TITLE
add menu for archiving of reports

### ISSUE THREAD

**Issue by nickreich** [reichlab/variant-nowcast-hub-dashboard#4]
e.g. site-config.yml could be something like

```
---
hub: "reichlab/variant-nowcast-hub"
title: "SARS-CoV-2 Variant Nowcast Hub"
pages:
  - text: "reports"
    menu:
    - "report.md"
    - "report2.md"
```
